### ISSUE TITLE
First run issue

### ISSUE THREAD

**Issue by Undefined3301** [tungdo0602/Discord-Token-Cracker#13]
Hi there :) 

I've had this issue since I'm trying to run.bat or python main.py (proxy grabber worked well), I have python 3.10, installed console with pip ... Can't figure out where the problems come from :
![image](https://user-images.githubusercontent.com/26310745/156818617-7c433c9a-450b-4eb7-9d39-592e1eb2c816.png)

Thanks in advance for your assistance :D

**Comment by tungdo0602** [comment]
to fix that issue you need to open the config.json file and delete all content in it. Next, run run.bat and then close it and you'll see the config will generate and edit it or run file

**Comment by Undefined3301** [comment]
It worked !
I had an empty line in the config, thanks :D !
