### ISSUE TITLE
can i have help pls

### ISSUE THREAD

**Issue by 0verTube** [tungdo0602/Discord-Token-Cracker#16]
Traceback (most recent call last):
  File "C:\Users\OverTube\Desktop\Discord-Token-Cracker-main\Generator\main.py", line 44, in <module>
    with open(data["socks4.txt"], "r") as file:
TypeError: string indices must be integers 

my error

**Comment by TavisHemn201** [comment]
I Have the same issue I went over the code and converted everything and tried out, still didn't work if anyone have a solution for this problem please let us know!
