### ISSUE TITLE
No import module

### ISSUE THREAD

**Issue by LCannotMLG** [tungdo0602/Discord-Token-Cracker#18]
![Screenshot_20230108_084119](https://user-images.githubusercontent.com/84139651/211199318-7eb3aaee-b55f-4436-8b69-5cbee39b7e31.png)

I run it for the first time and this then I downloaded the proxy and it is still doing this.

**Comment by LCannotMLG** [comment]
I'm dumb

**Comment by LCannotMLG** [comment]
I can't open main.py too it just immediately closes.

**Comment by tungdo0602** [comment]
`pip install console`

i forgot to put it in the requirement.txt lol

**Comment by tungdo0602** [comment]
> I can't open main.py too it just immediately closes.

first you need to install the requirement packages
