### ISSUE TITLE
How exactly does the done.txt work?

### ISSUE THREAD

**Issue by Mustard132** [tungdo0602/Discord-Token-Cracker#3]
I have let the token generator do its things for a few days but on some occasions it just stops working and somehow closes itself. i noticed that there was a done.txt document in the folder but its always empty. Why is this the case? I thought it would store the tokens

**Comment by tungdo0602** [comment]
it close bc ur connection get close or something that make it timeout too long and it will close, and if the cracker done it will break the loop and stop at correct token (write to file too)
