### ISSUE TITLE
Tons of bad proxies

### ISSUE THREAD

**Issue by NotMifa** [tungdo0602/Discord-Token-Cracker#4]
Im following all the instructions but on my cmd window, it only shows total proxies as 5035 and bad proxies as 140395 and going on. Any fixes? im using a vm btw

**Comment by WISH12345** [comment]
Free proxies are always bad there's nothing you can do. I used uproxy to check 8k free proxies and only 60 were working.

**Comment by tungdo0602** [comment]
ik lol

**Comment by almadrasa** [comment]
how to use proxies with username and password?
