### ISSUE TITLE
Problems with run.bat

### ISSUE THREAD

**Issue by tantypanty** [tungdo0602/Discord-Token-Cracker#5]
When I run run.bat I get this error

![image](https://user-images.githubusercontent.com/84468444/150673322-6bb5f343-d519-4f55-8a0f-a3272bcc3176.png)

Ideas on how to fix this?

**Comment by tungdo0602** [comment]
because you missing the module console

**Comment by tungdo0602** [comment]
use "pip install console"

**Comment by tantypanty** [comment]
Thank you tung :) 
How often does this get a valid token?
