### ISSUE TITLE
is this normal

### ISSUE THREAD

**Issue by EmpathyYT** [tungdo0602/Discord-Token-Cracker#6]
is having 800k bad proxies and no invalid/valid tokens normal? i know free proxies are bad but are they that bad?

**Comment by tungdo0602** [comment]
you can change the time out to more second, i think some proxy are too slow to respond and the program skip it

**Comment by EmpathyYT** [comment]
so adding another 1k to the timeout param

**Comment by tungdo0602** [comment]
1000ms = 1 second

**Comment by tungdo0602** [comment]
1000 in the timeout mean 1000 ms

**Comment by EmpathyYT** [comment]
alright got it thanks
