### ISSUE TITLE
READ

### ISSUE THREAD

**Issue by ENDERM4NQ** [tungdo0602/Discord-Token-Cracker#9]
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    if data["cracker_mode"] == "user":
KeyError: 'cracker_mode'

**Comment by ENDERM4NQ** [comment]
update fix the capitilization in main.py (config & main.py)

**Comment by tungdo0602** [comment]
ok

**Comment by tungdo0602** [comment]
fixed
